// app/_lib/services-cities-unique.js
// Per-pair unique content for the top Service×City combinations.
// Adds a paragraph specific to the intersection (city tax/market + service strategy),
// rendered above the generic template content. Pairs without an entry fall back to
// the generic template only.
//
// Key format: `<serviceSlug>:<citySlug>` (matches keys in services-cities.ts).

import type { Locale } from "./services-cities";

type PairEntry = Partial<Record<Locale, string>>;

export const PAIR_CONTENT: Record<string, PairEntry> = {
  // ─── TFSA × Calgary ─────────────────────────────────────────────────────
  "tfsa:calgary": {
    uk: `Калгарі — найшвидше зростаюче місто Канади, і це впливає на TFSA-стратегію двома способами. По-перше, **Alberta flat 10% provincial tax** на низькі/середні брекети означає що різниця між TFSA і RRSP у твої перші роки тут менш виражена ніж у BC/Ontario — тобто TFSA пріоритет ще сильніший. По-друге, при household income ~$116K (медіана Calgary CMA) і 3-5 роках у Канаді ти швидко стаєш **Eligible Investor**, що відкриває доступ до Calgary-фокусованих exempt market фондів — multi-family rentals, industrial syndications, mixed-use developments у Mission/Beltline. У TFSA такі продукти ростуть **повністю tax-free**, що при historical 7-10% IRR за 15 років робить різницю в $80-150K порівняно з ETF.`,
    ru: `Калгари — самый быстрорастущий город Канады, и это влияет на TFSA-стратегию двумя способами. Во-первых, **Alberta flat 10% provincial tax** на низкие/средние брекеты означает что разница между TFSA и RRSP в твои первые годы здесь менее выражена чем в BC/Ontario — то есть TFSA приоритет ещё сильнее. Во-вторых, при household income ~$116K (медиана Calgary CMA) и 3-5 годах в Канаде ты быстро становишься **Eligible Investor**, что открывает доступ к Calgary-сфокусированным exempt market фондам — multi-family rentals, industrial syndications, mixed-use developments в Mission/Beltline. В TFSA такие продукты растут **полностью tax-free**, что при historical 7-10% IRR за 15 лет даёт разницу в $80-150K по сравнению с ETF.`,
    en: `Calgary is Canada's fastest-growing major city, and that shapes TFSA strategy in two ways. First, **Alberta's flat 10% provincial tax** on low/middle brackets makes the gap between TFSA and RRSP narrower in your early years here than in BC/Ontario — meaning the TFSA-first priority is even more clear-cut. Second, at the Calgary CMA median household income (~$116K) plus 3-5 years in Canada, you cross into **Eligible Investor** status quickly, which unlocks Calgary-focused exempt market funds — multi-family rentals, industrial syndications, mixed-use developments in Mission/Beltline. Inside a TFSA those products grow **fully tax-free**, which at historical 7-10% IRR over 15 years compounds into an $80-150K difference vs ETFs alone.`,
  },

  // ─── FHSA × Calgary ─────────────────────────────────────────────────────
  "fhsa:calgary": {
    uk: `У Калгарі FHSA — найпотужніший інструмент для першого дому. Середня ціна townhouse тут $480K, condo $360K — це означає що **повністю максимізована пара FHSA ($40K) + RRSP HBP ($60K) = $100K** покриває 20% down payment на дім $500K без CMHC premium ($19K економії). Подружжя × 2 = $200K → дім $1M під 20%. Плюс **Alberta не має land transfer tax** (тоді як Ontario бере 1.5-2% при покупці) — це додаткова економія $5-15K на типовому домі. Стратегія: відкрий FHSA одразу (room починається з відкриття), вноси $8K/рік 5 років, паралельно накопичуй RRSP до HBP-ліміту, через 5 років маєш $100K-180K готівкою на покупку — без CMHC, без land transfer tax, без податку.`,
    ru: `В Калгари FHSA — самый мощный инструмент для первого дома. Средняя цена townhouse здесь $480K, condo $360K — это означает что **полностью максимизированная пара FHSA ($40K) + RRSP HBP ($60K) = $100K** покрывает 20% down payment на дом $500K без CMHC premium ($19K экономии). Супруги × 2 = $200K → дом $1M под 20%. Плюс **Alberta не имеет land transfer tax** (тогда как Ontario берёт 1.5-2% при покупке) — это дополнительная экономия $5-15K на типичном доме. Стратегия: открой FHSA сразу (room начинается с открытия), вноси $8K/год 5 лет, параллельно накапливай RRSP до HBP-лимита, через 5 лет имеешь $100K-180K наличными на покупку — без CMHC, без land transfer tax, без налога.`,
    en: `In Calgary, FHSA is the most powerful first-home tool. The average townhouse here runs $480K, condo $360K — meaning a **fully maxed FHSA ($40K) + RRSP HBP ($60K) = $100K** covers a 20% down payment on a $500K home with no CMHC premium ($19K saved). A couple × 2 = $200K → $1M home at 20%. Plus **Alberta has no land transfer tax** (whereas Ontario charges 1.5-2% on purchase) — that's another $5-15K saved on a typical home. The play: open FHSA immediately (room starts at opening), contribute $8K/year for 5 years, accumulate RRSP toward HBP in parallel — in 5 years you have $100K-180K of cash ready to buy with no CMHC, no land transfer tax, no income tax.`,
  },

  // ─── Exempt market × Calgary ────────────────────────────────────────────
  "exempt-market:calgary": {
    uk: `Калгарі — мій home base і **найкращий ринок для exempt market у Канаді 2024-2026**. Чому конкретно: cap rates 5.5-7% (vs 3.5-4.5% у Toronto) дають **2× кращий cash-on-cash return** на той же type property. Plus +90K нових мешканців у 2024 (5% YoY growth) — попит на multi-family rentals, industrial warehouses, healthcare REE-проекти зростає швидше ніж supply. Категорії доступні через мене як EMD-радника: **Multi-family MICs/REITs** (Calgary SE, Edmonton, Red Deer — target IRR 8-12%), **Industrial syndications** (Foothills, Balzac логістика — target IRR 9-14% з 5-10 year contracted leases), **Mixed-use development LPs** (Mission, Beltline, East Village — target IRR 15-22%). Мінімум для Eligible Investor — $25-30K на offering. NRD #4575551, AB-зареєстрований — фізичні зустрічі у Calgary head office.`,
    ru: `Калгари — мой home base и **лучший рынок для exempt market в Канаде 2024-2026**. Почему конкретно: cap rates 5.5-7% (vs 3.5-4.5% в Toronto) дают **2× лучший cash-on-cash return** на тот же type property. Plus +90K новых жителей в 2024 (5% YoY growth) — спрос на multi-family rentals, industrial warehouses, healthcare RE-проекты растёт быстрее чем supply. Категории доступные через меня как EMD-советника: **Multi-family MICs/REITs** (Calgary SE, Edmonton, Red Deer — target IRR 8-12%), **Industrial syndications** (Foothills, Balzac логистика — target IRR 9-14% с 5-10 year contracted leases), **Mixed-use development LPs** (Mission, Beltline, East Village — target IRR 15-22%). Минимум для Eligible Investor — $25-30K на offering. NRD #4575551, AB-зарегистрирован — физические встречи в Calgary head office.`,
    en: `Calgary is my home base and **Canada's best exempt market in 2024-2026**. Concretely: cap rates 5.5-7% (vs 3.5-4.5% in Toronto) deliver **2× better cash-on-cash returns** on the same property type. Plus +90K new residents in 2024 (5% YoY growth) — demand for multi-family rentals, industrial warehouses, healthcare RE projects is outpacing supply. Categories available through me as your EMD advisor: **Multi-family MICs/REITs** (Calgary SE, Edmonton, Red Deer — target IRR 8-12%), **Industrial syndications** (Foothills, Balzac logistics — target IRR 9-14% with 5-10 year contracted leases), **Mixed-use development LPs** (Mission, Beltline, East Village — target IRR 15-22%). Eligible Investor minimum — $25-30K per offering. NRD #4575551, AB-registered — in-person meetings at Calgary head office.`,
  },

  // ─── TFSA × Edmonton ────────────────────────────────────────────────────
  "tfsa:edmonton": {
    uk: `Едмонтон має ту ж Alberta tax advantage що й Калгарі (flat 10% provincial), але housing на ~30% дешевше — це звільняє більше cash flow для **максимізації TFSA**. При median household income ~$108K і дешевшому житлі, едмонтонські новоприбулі зазвичай можуть вкласти $7K у TFSA вже на 2-3 рік (швидше ніж у Vancouver/Toronto де rent з'їдає cash). Government + healthcare jobs у Едмонтоні дають stable T4 income — це ідеально для TFSA стратегії monthly contributions. Через 5 років при $7K/рік + 8% growth у broad-market ETF — ~$50K у TFSA. Далі при income $75K+ відкривається exempt market через TFSA wrapper — distributions tax-free.`,
    ru: `Эдмонтон имеет то же Alberta tax advantage что и Калгари (flat 10% provincial), но housing на ~30% дешевле — это освобождает больше cash flow для **максимизации TFSA**. При median household income ~$108K и более дешёвом жилье, эдмонтонские новоприбывшие обычно могут вложить $7K в TFSA уже на 2-3 год (быстрее чем в Vancouver/Toronto где rent съедает cash). Government + healthcare jobs в Эдмонтоне дают stable T4 income — это идеально для TFSA стратегии monthly contributions. Через 5 лет при $7K/год + 8% growth в broad-market ETF — ~$50K в TFSA. Дальше при income $75K+ открывается exempt market через TFSA wrapper — distributions tax-free.`,
    en: `Edmonton has the same Alberta tax advantage as Calgary (flat 10% provincial), but housing is ~30% cheaper — freeing up more cash flow for **maxing out TFSA**. At median household income ~$108K and lower rent, Edmonton newcomers can typically max $7K to TFSA by year 2-3 (faster than in Vancouver/Toronto where rent eats cash). Government + healthcare jobs in Edmonton deliver stable T4 income — perfect for a TFSA monthly-contributions strategy. After 5 years at $7K/year + 8% growth in a broad-market ETF — ~$50K inside TFSA. Then at income $75K+ exempt market unlocks via the TFSA wrapper — distributions tax-free.`,
  },

  // ─── FHSA × Edmonton ────────────────────────────────────────────────────
  "fhsa:edmonton": {
    uk: `Едмонтон — мабуть **найкраще місто Канади для FHSA-стратегії**. Чому: середня ціна condo $250-300K, townhouse $350-400K — а максимальний FHSA + RRSP HBP комбо ($100K solo, $200K couple) **повністю покриває** 20-30% down payment без CMHC. По суті 5 років акумуляції — і ти власник дому без жодного податку на накопичення down payment. Plus no land transfer tax + Alberta flat 10% — closing costs мінімальні. Government + university jobs дають perfect T4 historu для mortgage qualifying. У Калгарі ти може дозволиш townhouse — у Едмонтоні з тим самим down payment **detached дім у good neighborhood**.`,
    ru: `Эдмонтон — пожалуй **лучший город Канады для FHSA-стратегии**. Почему: средняя цена condo $250-300K, townhouse $350-400K — а максимальный FHSA + RRSP HBP комбо ($100K solo, $200K couple) **полностью покрывает** 20-30% down payment без CMHC. По сути 5 лет аккумуляции — и ты владелец дома без какого-либо налога на накопление down payment. Plus no land transfer tax + Alberta flat 10% — closing costs минимальные. Government + university jobs дают perfect T4 history для mortgage qualifying. В Калгари ты может позволишь townhouse — в Эдмонтоне с тем же down payment **detached дом в good neighborhood**.`,
    en: `Edmonton is arguably **the best Canadian city for an FHSA strategy**. Why: average condo $250-300K, townhouse $350-400K — and the maxed FHSA + RRSP HBP combo ($100K solo, $200K couple) **fully covers** a 20-30% down payment with no CMHC. In effect 5 years of accumulation = homeownership with zero tax on the down payment. Plus no land transfer tax + Alberta's flat 10% — closing costs are minimal. Government + university jobs deliver perfect T4 history for mortgage qualifying. In Calgary the same money buys a townhouse — in Edmonton it buys a **detached home in a good neighborhood**.`,
  },

  // ─── TFSA × Toronto ─────────────────────────────────────────────────────
  "tfsa:toronto": {
    uk: `Торонто має **найбільшу українську діаспору в Канаді (1M+)** і high cost of living, що змінює TFSA-калкуляцію. По-перше, Ontario top marginal rate 13.16% (провінційний) + federal = до 53.5% — тобто на високих брекетах RRSP стає дуже привабливим, але **TFSA все одно повинен бути максимізований першим** як emergency / flexibility buffer. По-друге, real estate $1,200+/sq.ft. означає що **shift у бік exempt market REIT** у TFSA робить більше сенсу ніж фізична нерухомість для більшості — твої $50K у Calgary multi-family REIT через TFSA дають доступ до 5.5-7% cap rates Calgary без $1M+ Toronto purchase price. Це особливо актуально для торонто-newcomer-ів які хочуть real estate exposure без overpaying у власному ринку.`,
    ru: `Торонто имеет **крупнейшую русскоязычную и украинскую диаспору в Канаде (1M+)** и high cost of living, что меняет TFSA-калькуляцию. Во-первых, Ontario top marginal rate 13.16% (провинциальный) + federal = до 53.5% — то есть на высоких брекетах RRSP становится очень привлекательным, но **TFSA всё равно должен быть максимизирован первым** как emergency / flexibility buffer. Во-вторых, real estate $1,200+/sq.ft. означает что **shift в сторону exempt market REIT** в TFSA имеет больше смысла чем физическая недвижимость для большинства — твои $50K в Calgary multi-family REIT через TFSA дают доступ к 5.5-7% cap rates Calgary без $1M+ Toronto purchase price. Это особенно актуально для торонто-newcomer-ов которые хотят real estate exposure без overpaying в собственном рынке.`,
    en: `Toronto has **Canada's largest Ukrainian/Russian-speaking diaspora (1M+)** and high cost of living, which changes the TFSA calculus. First, Ontario's top marginal rate of 13.16% (provincial) + federal = up to 53.5% — so at high brackets RRSP becomes very attractive, but **TFSA should still be maxed first** as an emergency / flexibility buffer. Second, real estate at $1,200+/sq.ft. means a **shift toward exempt market REITs** inside TFSA makes more sense than physical real estate for most — your $50K in a Calgary multi-family REIT via TFSA gives you 5.5-7% cap-rate exposure without a $1M+ Toronto purchase price. Especially relevant for Toronto newcomers wanting real estate exposure without overpaying in their own market.`,
  },

  // ─── RRSP × Toronto ─────────────────────────────────────────────────────
  "rrsp:toronto": {
    uk: `Торонто — місто де **RRSP працює найкраще** через Ontario progressive tax bracket. При income $130K+ marginal rate ~43%, при $250K+ — ~53.5%. Тобто на кожні $10K у RRSP економиш **$4,300-$5,350 у tax refund цього року**. Reinvested refund сам генерує приріст. Стратегія для Toronto high-earner: max RRSP ($32K у 2026) → отримуєш ~$15K refund → reinvest у TFSA. Через 10 років compound на reinvested refunds сам по собі генерує $150K+. Plus **Ontario має RRSP HBP $60K** як backup для дому. На пенсії marginal rate буде 25-30% (нижчий бо немає T4) → RRSP виграє у net-after-tax порівнянні з TFSA. Виняток — якщо плануєш повернутись в Україну / переїхати у Альберту до пенсії — TFSA пріоритет (бо RRSP withdraw з-за кордону складніший).`,
    ru: `Торонто — город где **RRSP работает лучше всего** из-за Ontario progressive tax bracket. При income $130K+ marginal rate ~43%, при $250K+ — ~53.5%. То есть на каждые $10K в RRSP экономишь **$4,300-$5,350 в tax refund этого года**. Reinvested refund сам генерирует прирост. Стратегия для Toronto high-earner: max RRSP ($32K в 2026) → получаешь ~$15K refund → reinvest в TFSA. Через 10 лет compound на reinvested refunds сам по себе генерирует $150K+. Plus **Ontario имеет RRSP HBP $60K** как backup для дома. На пенсии marginal rate будет 25-30% (ниже потому что нет T4) → RRSP выигрывает в net-after-tax сравнении с TFSA. Исключение — если планируешь вернуться в Россию/Украину или переехать в Альберту до пенсии — TFSA приоритет (потому что RRSP withdraw из-за рубежа сложнее).`,
    en: `Toronto is where **RRSP works best**, thanks to Ontario's progressive tax brackets. At income $130K+ marginal rate is ~43%; at $250K+ — ~53.5%. So every $10K into RRSP saves you **$4,300-$5,350 in current-year tax refund**. The reinvested refund compounds on its own. Strategy for Toronto high-earners: max RRSP ($32K in 2026) → receive ~$15K refund → reinvest into TFSA. Over 10 years the compounding refund alone generates $150K+. Plus **Ontario respects RRSP HBP $60K** as a home-buying backup. In retirement your marginal rate will be 25-30% (lower, no T4) → RRSP wins on net-after-tax vs TFSA. Exception — if you're planning to leave Canada or move to Alberta before retirement, TFSA-first instead (RRSP withdrawal from abroad is messier).`,
  },

  // ─── FHSA × Vancouver ───────────────────────────────────────────────────
  "fhsa:vancouver": {
    uk: `Ванкувер — **найдорожчий ринок Канади** ($1,400+/sq.ft., середній condo $700K-900K) і паралельно — місто де FHSA-стратегія **критично важлива**. Реальна математика: при типовій вартості $800K condo, 20% down payment = $160K. Один FHSA ($40K) + один RRSP HBP ($60K) = $100K solo, ще $60K треба з звичайних накопичень. Подружжя × 2 = $200K → повністю покриває down payment $1M condo без CMHC. Проти Calgary тут є додаткові виклики: **BC additional 2% property transfer tax** (PTT) на purchase понад $200K (vs $0 у Альберті), плюс **foreign buyer ban** і **speculation tax** обмежують short-term flipping. Для newcomer-ів стратегія: max FHSA з дня 1, max RRSP HBP за 3-5 років, паралельно tax-free накопичення у TFSA для closing costs $20-40K.`,
    ru: `Ванкувер — **самый дорогой рынок Канады** ($1,400+/sq.ft., средний condo $700K-900K) и параллельно — город где FHSA-стратегия **критически важна**. Реальная математика: при типичной стоимости $800K condo, 20% down payment = $160K. Один FHSA ($40K) + один RRSP HBP ($60K) = $100K solo, ещё $60K надо из обычных накоплений. Супруги × 2 = $200K → полностью покрывает down payment $1M condo без CMHC. Против Calgary здесь есть дополнительные вызовы: **BC additional 2% property transfer tax** (PTT) на purchase свыше $200K (vs $0 в Альберте), плюс **foreign buyer ban** и **speculation tax** ограничивают short-term flipping. Для newcomer-ов стратегия: max FHSA с дня 1, max RRSP HBP за 3-5 лет, параллельно tax-free накопление в TFSA для closing costs $20-40K.`,
    en: `Vancouver is **Canada's most expensive market** ($1,400+/sq.ft., average condo $700K-900K) and at the same time — a city where FHSA strategy is **critical**. The actual math: at a typical $800K condo, 20% down payment = $160K. One FHSA ($40K) + one RRSP HBP ($60K) = $100K solo; you still need another $60K from regular savings. A couple × 2 = $200K → fully covers the down payment on a $1M condo with no CMHC. Versus Calgary there are extra headwinds: **BC's 2% property transfer tax** on purchases above $200K (vs $0 in Alberta), plus **foreign buyer ban** and **speculation tax** that limit short-term flipping. For newcomers the play: max FHSA from day one, max RRSP HBP over 3-5 years, plus tax-free accumulation in TFSA for $20-40K of closing costs.`,
  },

  // ─── Exempt market × Toronto ────────────────────────────────────────────
  "exempt-market:toronto": {
    uk: `Торонто — **найбільший фінансовий ринок Канади** і місто з найбільшою кількістю exempt market offerings. Більшість major EMD-фірм базується тут — Axcess Capital Advisors (моя firm) має Ontario registration, тобто я можу працювати з тобою якщо ти resident ON. Особливості Toronto-orientation: **Ontario top tax 13.16% provincial** робить tax-sheltering через TFSA/RRSP wrapper для exempt market critical — distributions у non-registered account оподатковуються до 53.5%. **Cap rates Toronto низькі** (3.5-4.5%), тому Toronto-фокусовані фонди дають менший cash-on-cash return ніж Calgary-фокусовані; для income generation я часто пропоную Toronto-resident клієнтам **Calgary/Alberta-фокусовані MICs/REITs** (cap rates 5.5-7%) — диверсифікація + кращий yield. Discovery call для Toronto клієнта = Zoom (фізичні зустрічі тільки у Calgary head office).`,
    ru: `Торонто — **крупнейший финансовый рынок Канады** и город с наибольшим количеством exempt market offerings. Большинство major EMD-фирм базируется здесь — Axcess Capital Advisors (моя firm) имеет Ontario registration, то есть я могу работать с тобой если ты resident ON. Особенности Toronto-orientation: **Ontario top tax 13.16% provincial** делает tax-sheltering через TFSA/RRSP wrapper для exempt market critical — distributions в non-registered account облагаются до 53.5%. **Cap rates Toronto низкие** (3.5-4.5%), поэтому Toronto-сфокусированные фонды дают меньший cash-on-cash return чем Calgary-сфокусированные; для income generation я часто предлагаю Toronto-resident клиентам **Calgary/Alberta-сфокусированные MICs/REITs** (cap rates 5.5-7%) — диверсификация + лучший yield. Discovery call для Toronto клиента = Zoom (физические встречи только в Calgary head office).`,
    en: `Toronto is **Canada's largest financial market** and the city with the most exempt market offerings. Most major EMD firms are headquartered here — Axcess Capital Advisors (my firm) has Ontario registration, so I can work with you if you're ON-resident. Toronto-specific nuances: **Ontario's 13.16% provincial top tax** makes tax-sheltering exempt market via TFSA/RRSP wrappers critical — distributions in non-registered accounts are taxed up to 53.5%. **Toronto cap rates are low** (3.5-4.5%), so Toronto-focused funds yield lower cash-on-cash than Calgary-focused; for income generation I often recommend Toronto-resident clients **Calgary/Alberta-focused MICs/REITs** (cap rates 5.5-7%) — diversification + better yield. Discovery call for Toronto clients = Zoom (in-person meetings only at Calgary head office).`,
  },

  // ─── Exempt market × Edmonton ───────────────────────────────────────────
  "exempt-market:edmonton": {
    uk: `Едмонтон — столиця Альберти з government + healthcare-driven економікою. Це **ідеальна база для exempt market**: government секондмент клієнти типово мають 5-10+ років AB residency, накопичені TFSA/RRSP/FHSA, і стабільний T4-дохід вище $100K. Категорія Eligible Investor для більшості — питання 2-3 років. Edmonton-фокусовані offerings через Axcess Capital: **industrial syndications у Nisku/Sherwood Park/Foothills** (логістика, energy services — target IRR 9-13%), **healthcare REITs** (Royal Alex, Grey Nuns infrastructure — IRR 7-10%), **multi-family MICs** з фокусом на Edmonton metro (cap rates 6-7%, нижчі вакансії ніж Calgary). Перевага vs Calgary exempt market: ринок менш конкурентний, типові deal sizes менше ($5-15M LP raises), що дозволяє Eligible Investors з $25-50K увійти у meaningful position. Я як EMD-радник у AB можу запропонувати ці offerings прямо. NRD #4575551.`,
    ru: `Эдмонтон — столица Альберты с government + healthcare-driven экономикой. Это **идеальная база для exempt market**: government секондмент клиенты типично имеют 5-10+ лет AB residency, накопленные TFSA/RRSP/FHSA, и стабильный T4-доход выше $100K. Категория Eligible Investor для большинства — вопрос 2-3 лет. Edmonton-сфокусированные offerings через Axcess Capital: **industrial syndications в Nisku/Sherwood Park/Foothills** (логистика, energy services — target IRR 9-13%), **healthcare REITs** (Royal Alex, Grey Nuns infrastructure — IRR 7-10%), **multi-family MICs** с фокусом на Edmonton metro (cap rates 6-7%, ниже вакансии чем Calgary). Преимущество vs Calgary exempt market: рынок менее конкурентный, типичные deal sizes меньше ($5-15M LP raises), что позволяет Eligible Investors с $25-50K войти в meaningful position. Я как EMD-советник в AB могу предложить эти offerings прямо. NRD #4575551.`,
    en: `Edmonton — Alberta's capital with a government + healthcare-driven economy. It's an **ideal base for exempt market**: government secondment clients typically have 5-10+ years of AB residency, accumulated TFSA/RRSP/FHSA, and stable T4 income above $100K. Eligible Investor status for most is a 2-3 year question. Edmonton-focused offerings through Axcess Capital: **industrial syndications in Nisku/Sherwood Park/Foothills** (logistics, energy services — target IRR 9-13%), **healthcare REITs** (Royal Alex, Grey Nuns infrastructure — IRR 7-10%), **multi-family MICs** focused on Edmonton metro (cap rates 6-7%, lower vacancy than Calgary). Edge vs Calgary exempt market: less competitive market, smaller typical deal sizes ($5-15M LP raises), letting Eligible Investors enter meaningful positions with $25-50K. As an EMD advisor in AB, I can offer these directly. NRD #4575551.`,
  },

  // ─── FHSA × Toronto ─────────────────────────────────────────────────────
  "fhsa:toronto": {
    uk: `Торонто — найдорожчий ринок Канади для першого дому (середня ціна condo ~$750K, у downtown $1,200+/sq.ft.), але FHSA + RRSP HBP комбо **все одно рухає голку**. Конкретні цифри: пара з максимальним FHSA $80K + RRSP HBP $120K = **$200K down payment без CMHC premium**. На дім $1M під 20% це **повне покриття без insurance** ($23K економії). Унікальна Toronto-specific нюанс: **Ontario land transfer tax 1.5-2%** = $11K-15K додаткових closing costs (Alberta = $0). Стратегія: пріоритезуй FHSA першим (zero tax на ріст + покривається 100% при first home use), RRSP HBP як backup якщо FHSA вичерпано. У Торонто також **доступні Calgary-фокусовані MICs/REITs** через мене як EMD (cap rates 5.5-7% > Toronto 3.5-4.5%) — корисний tool для diversification якщо ти Eligible Investor.`,
    ru: `Торонто — самый дорогой рынок Канады для первого дома (средняя цена condo ~$750K, в downtown $1,200+/sq.ft.), но FHSA + RRSP HBP комбо **всё равно двигает иглу**. Конкретные цифры: пара с максимальным FHSA $80K + RRSP HBP $120K = **$200K down payment без CMHC premium**. На дом $1M под 20% это **полное покрытие без insurance** ($23K экономии). Уникальный Toronto-specific нюанс: **Ontario land transfer tax 1.5-2%** = $11K-15K дополнительных closing costs (Alberta = $0). Стратегия: приоритезируй FHSA первым (zero tax на рост + покрывается 100% при first home use), RRSP HBP как backup если FHSA исчерпан. В Торонто также **доступны Calgary-сфокусированные MICs/REITs** через меня как EMD (cap rates 5.5-7% > Toronto 3.5-4.5%) — полезный tool для diversification если ты Eligible Investor.`,
    en: `Toronto is Canada's most expensive first-home market (average condo ~$750K, downtown $1,200+/sq.ft.) — but the FHSA + RRSP HBP combo **still moves the needle**. Concrete numbers: a couple's maxed FHSA $80K + RRSP HBP $120K = **$200K down payment with no CMHC premium**. On a $1M home at 20% down that's **full coverage without insurance** ($23K saved). Unique Toronto-specific catch: **Ontario land transfer tax 1.5-2%** = $11K-15K extra closing costs (Alberta = $0). Strategy: prioritise FHSA first (zero tax on growth + covered 100% at first-home use), use RRSP HBP as backup if FHSA is exhausted. Toronto residents can also access **Calgary-focused MICs/REITs** through me as EMD (cap rates 5.5-7% > Toronto's 3.5-4.5%) — useful diversification tool if you're an Eligible Investor.`,
  },

  // ─── TFSA × Red Deer ────────────────────────────────────────────────────
  "tfsa:red-deer": {
    uk: `Ред-Дір — третє місто Альберти, **найдоступніший** для accumulation strategy. Median income ~$95K, housing $250-400K condo / $400-600K detached — економія на rent vs Калгарі/Едмонтон звільняє $500-1,000/міс для TFSA contributions. Та сама Alberta tax advantage (flat 10% provincial низькі brackets, no PST) — кожен $1,000 у TFSA = $0 податку на ріст vs ETF у non-registered где capital gains 50% inclusion при retiring. Стратегія: max $7K TFSA через 5 років (broad-market ETF — XEQT/VFV/VEQT) = ~$50K принципу + $15K growth. У 7-річний horizon це база для exempt market entry якщо доростеш до Eligible Investor ($75K solo income — типовий Red Deer healthcare/energy worker). Менша advisor competition тут робить особисту увагу легше — direct contact зі мною через Calendly або +1 (403) 397-2553.`,
    ru: `Ред-Дир — третий город Альберты, **наиболее доступный** для accumulation strategy. Median income ~$95K, housing $250-400K condo / $400-600K detached — экономия на rent vs Калгари/Эдмонтон освобождает $500-1,000/мес для TFSA contributions. Та же Alberta tax advantage (flat 10% provincial низкие brackets, no PST) — каждый $1,000 в TFSA = $0 налога на рост vs ETF в non-registered где capital gains 50% inclusion при retiring. Стратегия: max $7K TFSA через 5 лет (broad-market ETF — XEQT/VFV/VEQT) = ~$50K принципа + $15K growth. В 7-летнем horizon это база для exempt market entry если дорастёшь до Eligible Investor ($75K solo income — типичный Red Deer healthcare/energy worker). Меньшая advisor competition здесь делает персональное внимание легче — direct contact со мной через Calendly или +1 (403) 397-2553.`,
    en: `Red Deer — Alberta's third city, **the most affordable** for an accumulation strategy. Median income ~$95K, housing $250-400K condo / $400-600K detached — rent savings vs Calgary/Edmonton free up $500-1,000/month for TFSA contributions. Same Alberta tax advantage (flat 10% provincial low brackets, no PST) — every $1,000 in TFSA = $0 tax on growth vs an ETF in non-registered where capital gains have 50% inclusion at retirement. Strategy: max $7K TFSA for 5 years (broad-market ETF — XEQT/VFV/VEQT) = ~$50K principal + $15K growth. Over a 7-year horizon that's the base for exempt market entry once you reach Eligible Investor ($75K solo income — typical Red Deer healthcare/energy worker). Lower advisor competition here makes personal attention easier — direct contact via Calendly or +1 (403) 397-2553.`,
  },

  // ─── RRSP × Burnaby ─────────────────────────────────────────────────────
  "rrsp:burnaby": {
    uk: `Бернабі — другий за розміром BC, **tech corridor** (SAP HQ, Translink, BC Hydro). Combined federal + BC top marginal при $200K income = ~50%. Tech salary $150K-250K = sweet spot для RRSP-first стратегії — кожен $10K у RRSP = **$4,500-$5,000 immediate tax refund** який потім reinvest у TFSA для compound multiplication. Burnaby specific: housing ~20% дешевше за Vancouver proper (детачд $1.5M vs $1.8M у Van), що дозволяє більше cash flow для max RRSP $32K + max FHSA $8K + max TFSA $7K = **$47K у tax shelters/рік**. RSU-heavy tech compensation: RSU vesting events часто додають $50-100K додаткового income — RRSP стає critical для smoothing tax bill. Discovery call для Burnaby resident = Zoom.`,
    ru: `Бернаби — второй по размеру BC, **tech corridor** (SAP HQ, Translink, BC Hydro). Combined federal + BC top marginal при $200K income = ~50%. Tech salary $150K-250K = sweet spot для RRSP-first стратегии — каждый $10K в RRSP = **$4,500-$5,000 immediate tax refund** который потом reinvest в TFSA для compound multiplication. Burnaby specific: housing ~20% дешевле Vancouver proper (детачд $1.5M vs $1.8M в Van), что позволяет больше cash flow для max RRSP $32K + max FHSA $8K + max TFSA $7K = **$47K в tax shelters/год**. RSU-heavy tech compensation: RSU vesting events часто добавляют $50-100K дополнительного income — RRSP становится critical для smoothing tax bill. Discovery call для Burnaby resident = Zoom.`,
    en: `Burnaby — BC's second-largest city, the **tech corridor** (SAP HQ, Translink, BC Hydro). Combined federal + BC top marginal at $200K income = ~50%. Tech salaries $150K-250K = sweet spot for an RRSP-first strategy — each $10K into RRSP = **$4,500-$5,000 immediate tax refund** which then reinvests into TFSA for compound multiplication. Burnaby specific: housing ~20% cheaper than Vancouver proper (detached $1.5M vs $1.8M in Van), freeing up more cash flow for max RRSP $32K + max FHSA $8K + max TFSA $7K = **$47K in tax shelters/year**. RSU-heavy tech compensation: RSU vesting events often add $50-100K of extra income — RRSP becomes critical for smoothing the tax bill. Discovery call for Burnaby residents = Zoom.`,
  },

  // ─── TFSA × Vancouver ───────────────────────────────────────────────────
  "tfsa:vancouver": {
    uk: `Ванкувер — найдорожчий ринок Канади, і це робить TFSA **захисним інструментом** не просто growth vehicle. Median household income ~$90K + Vancouver cost-of-living = багато ванкуверських newcomer-ів не дозволяють собі max TFSA одразу. Стратегія: контрибутуй те що можеш ($200-500/міс) у broad-market ETF (XEQT, VEQT) — головне не сума, а **початок compounding clock**. BC progressive tax 16.8-20.5% на високих брекетах означає що RRSP ставатиме привабливим раніше (від ~$130K income), але **TFSA flexibility** критичний у дорогому ринку де unexpected expenses (rent jump, vet bill, car repair) можуть з'їсти 6-12 місяців budget.`,
    ru: `Ванкувер — самый дорогой рынок Канады, и это делает TFSA **защитным инструментом**, не просто growth vehicle. Median household income ~$90K + Vancouver cost-of-living = многие ванкуверские newcomer-ы не позволяют себе max TFSA сразу. Стратегия: контрибутируй то что можешь ($200-500/мес) в broad-market ETF (XEQT, VEQT) — главное не сумма, а **начало compounding clock**. BC progressive tax 16.8-20.5% на высоких брекетах означает что RRSP станет привлекательным раньше (от ~$130K income), но **TFSA flexibility** критична в дорогом рынке.`,
    en: `Vancouver is Canada's most expensive market, and that makes TFSA a **defensive tool**, not just a growth vehicle. Median household income ~$90K + Vancouver cost-of-living = many Vancouver newcomers can't max TFSA right away. Strategy: contribute what you can ($200-500/mo) into a broad-market ETF (XEQT, VEQT) — the amount matters less than **starting the compounding clock**. BC's progressive tax 16.8-20.5% at high brackets means RRSP becomes attractive earlier (from ~$130K income), but **TFSA flexibility** is critical in an expensive market where unexpected expenses can eat 6-12 months of budget.`,
  },

  // ─── TFSA × Burnaby ─────────────────────────────────────────────────────
  "tfsa:burnaby": {
    uk: `Бернабі — Vancouver's tech corridor (Microsoft, SAP campuses), що означає **багато high-income engineers + IT consultants** серед русскомовних newcomers. При $130K+ T4 income з US-based remote роботи (типово через CUAET-relocations) TFSA-стратегія міняється: твоє room починається пізно (після tax-resident статусу), але **швидко катапультується** через high contributions ($7K/рік) + RSU sales reinvested. Якщо у тебе RSU vesting у US tech employer — продай і одразу клади у TFSA до ліміту, потім у non-registered. TFSA tax-free growth на $35K за 5 років (5 × $7K) + 8% IRR = ~$45K — це **$7-10K економії податку** на capital gains порівняно з non-registered.`,
    ru: `Бернаби — Vancouver's tech corridor (Microsoft, SAP campuses), что означает **много high-income engineers + IT consultants** среди русскоязычных newcomers. При $130K+ T4 income с US-based remote работы (типично через CUAET-relocations) TFSA-стратегия меняется: твоё room начинается поздно (после tax-resident статуса), но **быстро катапультируется** через high contributions ($7K/год) + RSU sales reinvested. Если у тебя RSU vesting в US tech employer — продай и сразу клади в TFSA до лимита, потом в non-registered.`,
    en: `Burnaby is Vancouver's tech corridor (Microsoft, SAP campuses) — meaning **lots of high-income engineers + IT consultants** among Russian/Ukrainian-speaking newcomers. At $130K+ T4 from US-based remote work (typical via CUAET relocations), TFSA strategy shifts: your room starts late (post-tax-residency) but **catapults fast** with high contributions ($7K/year) + RSU sales reinvested. If you have RSU vesting at a US tech employer — sell immediately and park in TFSA up to limit, then non-registered. TFSA tax-free growth on $35K over 5 years (5 × $7K) + 8% IRR = ~$45K — **$7-10K tax saved** on capital gains vs non-registered.`,
  },

  // ─── RRSP × Calgary ─────────────────────────────────────────────────────
  "rrsp:calgary": {
    uk: `У Калгарі RRSP **менш агресивно потужний** ніж у BC/Ontario через Alberta flat 10% provincial tax. На income $80K твоя marginal ~30%, на $150K — ~36%. Кожні $10K у RRSP = $3,000-$3,600 refund (vs $5,000 у Vancouver). Strategy: TFSA-first до age 30-35 (поки income низький), потім pivot до RRSP коли income > $130K — типово коли engineering / financial services / oil&gas senior. **Виняток**: якщо у тебе RSU vesting event ($50K+ за рік) — max RRSP того конкретного року для збиття marginal з 47% до 36%. Calgary також має сильну **HBP play**: average detached дім $550-650K, FHSA+HBP комбо ($100K solo / $200K couple) **уже покриває 15-30% down payment**.`,
    ru: `В Калгари RRSP **менее агрессивно мощный** чем в BC/Ontario из-за Alberta flat 10% provincial tax. На income $80K твоя marginal ~30%, на $150K — ~36%. Каждые $10K в RRSP = $3,000-$3,600 refund (vs $5,000 в Vancouver). Strategy: TFSA-first до age 30-35 (пока income низкий), потом pivot к RRSP когда income > $130K. **Исключение**: если у тебя RSU vesting event ($50K+ за год) — max RRSP того конкретного года для сбития marginal с 47% до 36%.`,
    en: `In Calgary, RRSP is **less aggressively powerful** than in BC/Ontario because of Alberta's flat 10% provincial tax. At $80K income your marginal is ~30%, at $150K ~36%. Every $10K into RRSP = $3,000-$3,600 refund (vs $5,000 in Vancouver). Strategy: TFSA-first to age 30-35 (while income is low), then pivot to RRSP when income > $130K — typically engineering / financial services / oil&gas seniors. **Exception**: if you have an RSU vesting event ($50K+ in a year) — max RRSP that specific year to knock marginal from 47% down to 36%. Calgary also has a strong **HBP play**: average detached home $550-650K, FHSA+HBP combo ($100K solo / $200K couple) **already covers 15-30% down payment**.`,
  },

  // ─── RRSP × Edmonton ────────────────────────────────────────────────────
  "rrsp:edmonton": {
    uk: `Едмонтонські RRSP-стратегії схожі з Calgary (Alberta flat tax), але з нюансом: **government + university workers** мають вже existing pension plans (RPP / IPP), що зменшує RRSP room. Перевір на NoA рядок "Pension Adjustment" — він безпосередньо зменшує твою RRSP contribution room. Якщо ти у Alberta Health Services, University of Alberta, або provincial government — у тебе вже сильне pension покриття, і **TFSA пріоритет ще сильніший** ніж RRSP. Для приватного сектору (energy services, healthcare practitioners) RRSP працює стандартно: контрибуй до 18% earned income, спрямовуй refund у TFSA + FHSA. Едмонтонські median income $108K → стандартний $32K RRSP cap не досягається, але $15-20K реалістично.`,
    ru: `Эдмонтонские RRSP-стратегии похожи с Calgary (Alberta flat tax), но с нюансом: **government + university workers** имеют уже existing pension plans (RPP / IPP), что уменьшает RRSP room. Проверь на NoA строку "Pension Adjustment" — она напрямую уменьшает твою RRSP contribution room. Если ты в Alberta Health Services, University of Alberta — у тебя уже сильное pension покрытие, и **TFSA приоритет ещё сильнее** чем RRSP.`,
    en: `Edmonton RRSP strategies mirror Calgary (Alberta flat tax), with one nuance: **government + university workers** already have existing pension plans (RPP / IPP), which reduces RRSP room. Check the "Pension Adjustment" line on your NoA — it directly reduces RRSP contribution room. If you're at Alberta Health Services, University of Alberta, or provincial government — you already have strong pension coverage, and **TFSA priority is even stronger** than RRSP. For private sector (energy services, healthcare practitioners) RRSP works standard: contribute up to 18% of earned income, redirect refund into TFSA + FHSA.`,
  },

  // ─── RRSP × Red Deer ────────────────────────────────────────────────────
  "rrsp:red-deer": {
    uk: `Ред-Дір — менший ринок (100K population) з median income ~$95K, тому RRSP-стратегія тут **простіша** але не менш важлива. Більшість Red Deer workers у energy services, agriculture, healthcare — типово T4 без pension. RRSP room повністю доступний кожен рік. Стратегія: 10-15% earned income у RRSP щорічно, спрямовуй refund у TFSA. Через 25-30 років compounding (відносно дешева median property у Red Deer = більше disposable income для RRSP) — comfortable retirement без потреби у corporate structures. Якщо ти small business owner у Red Deer (типово energy/agriculture support businesses) — розглянь CCPC + IPP, але це окремий гайд.`,
    ru: `Ред-Дир — меньший рынок (100K population) с median income ~$95K, поэтому RRSP-стратегия здесь **проще** но не менее важна. Большинство Red Deer workers в energy services, agriculture, healthcare — типично T4 без pension. RRSP room полностью доступен каждый год. Стратегия: 10-15% earned income в RRSP ежегодно, направляй refund в TFSA.`,
    en: `Red Deer is a smaller market (100K population) with median income ~$95K, so RRSP strategy here is **simpler** but no less important. Most Red Deer workers are in energy services, agriculture, healthcare — typically T4 without pension. RRSP room is fully available each year. Strategy: 10-15% of earned income into RRSP annually, redirect refund into TFSA. Over 25-30 years of compounding (relatively cheap median property in Red Deer = more disposable income for RRSP) — comfortable retirement without needing corporate structures.`,
  },

  // ─── FHSA × Red Deer ────────────────────────────────────────────────────
  "fhsa:red-deer": {
    uk: `Ред-Дір — місто де FHSA + savings можуть купити **detached дім за 3-4 роки** замість 7-10. Average detached тут $400-600K (vs $550-650K у Калгарі, $800K+ у Ванкувері). FHSA $40K solo + RRSP HBP $60K = $100K готівкою — це 17-25% down payment на $500K дім. Подружжя × 2 = $200K = повністю покриває 20% navet на $1M дім. Plus Alberta no land transfer tax + low closing costs ($3-5K total). Red Deer ідеальний для **молодих сімей з 2 дітьми** які хочуть власний дім швидко без overpaying за Calgary/Edmonton.`,
    ru: `Ред-Дир — город где FHSA + savings могут купить **detached дом за 3-4 года** вместо 7-10. Average detached здесь $400-600K. FHSA $40K solo + RRSP HBP $60K = $100K cash — это 17-25% down payment на $500K дом. Супруги × 2 = $200K = полностью покрывает 20% на $1M дом.`,
    en: `Red Deer is where FHSA + savings can buy you a **detached home in 3-4 years** instead of 7-10. Average detached here $400-600K (vs $550-650K in Calgary, $800K+ in Vancouver). FHSA $40K solo + RRSP HBP $60K = $100K cash — that's 17-25% down payment on a $500K home. A couple × 2 = $200K = fully covers 20% on a $1M home. Plus Alberta no land transfer tax + low closing costs ($3-5K total). Red Deer is ideal for **young families with 2 kids** who want homeownership fast without overpaying for Calgary/Edmonton.`,
  },

  // ─── FHSA × Burnaby ─────────────────────────────────────────────────────
  "fhsa:burnaby": {
    uk: `У Бернабі FHSA — **критичний** інструмент через high Vancouver-area prices. Average condo $700-900K, townhouse $1.1M+. FHSA $40K solo + RRSP HBP $60K = $100K — це лише 11-14% down payment на $800K condo (тобто треба ще додаткове $50-60K savings до 20% threshold для avoid CMHC). Стратегія Burnaby couple: обидва max FHSA + RRSP HBP = $200K тотал → 25% down на $800K condo або 20% на $1M townhouse. BC має land transfer tax (1% перший $200K, 2% решта до $2M), що додає $14-20K до closing — план FHSA на цю extra cost.`,
    ru: `В Бернаби FHSA — **критический** инструмент из-за high Vancouver-area prices. Average condo $700-900K, townhouse $1.1M+. FHSA $40K solo + RRSP HBP $60K = $100K — это лишь 11-14% down payment на $800K condo. Стратегия Burnaby couple: оба max FHSA + RRSP HBP = $200K тотал → 25% down на $800K condo.`,
    en: `In Burnaby FHSA is **critical** because of high Vancouver-area prices. Average condo $700-900K, townhouse $1.1M+. FHSA $40K solo + RRSP HBP $60K = $100K — that's only 11-14% down payment on an $800K condo (so you need another $50-60K in savings to clear the 20% threshold and avoid CMHC). Burnaby couple strategy: both max FHSA + RRSP HBP = $200K total → 25% down on $800K condo or 20% on $1M townhouse. BC has a land transfer tax (1% on first $200K, 2% on remainder up to $2M), adding $14-20K to closing — plan FHSA for this extra cost.`,
  },

  // ─── Exempt market × Red Deer ───────────────────────────────────────────
  "exempt-market:red-deer": {
    uk: `Ред-Дір як ринок exempt market працює через **portfolio diversification**, не як primary geography. Sense: коли ти живеш у Red Deer + working in stable T4 (energy services, healthcare) — твій income concentration ризик уже high (oil-price-dependent local economy). Exempt market дає diversification поза цей local risk. Якщо ти Eligible Investor (~$75K income solo / $400K assets) — типово через 3-4 рік оф у Канаді при професійних salaries — exempt market multi-family REIT у Calgary/Edmonton дає тобі **cap rate exposure 5.5-7%** без потреби фізично managing properties. Альтернатива: industrial syndications у Foothills area (logistics серцем Альберти).`,
    ru: `Ред-Дир как рынок exempt market работает через **portfolio diversification**, не как primary geography. Sense: когда ты живёшь в Red Deer + working in stable T4 — твой income concentration риск уже high (oil-price-dependent local economy). Exempt market даёт diversification вне этого local risk.`,
    en: `Red Deer as exempt market market works via **portfolio diversification**, not as primary geography. Sense: when you live in Red Deer + working stable T4 (energy services, healthcare) — your income concentration risk is already high (oil-price-dependent local economy). Exempt market gives diversification outside this local risk. If you're Eligible Investor (~$75K income solo / $400K assets) — typically by year 3-4 in Canada at professional salaries — exempt market multi-family REIT in Calgary/Edmonton gives you **cap rate exposure 5.5-7%** without physically managing properties. Alternative: industrial syndications in Foothills area (Alberta's logistics heartland).`,
  },

  // ─── Exempt market × Vancouver ──────────────────────────────────────────
  "exempt-market:vancouver": {
    uk: `Ванкувер — найвища концентрація **Accredited Investor-ів** в Канаді (через high real estate equity у Vancouver homeowners), але **парадокс**: BC exempt market дуже **обмежений** через high prices + low cap rates. Більшість Vancouver-based exempt market opportunities = **private credit** (debt to BC developers), не equity ownership. Краща стратегія для Vancouver high-net-worth: **diversify до Calgary/Edmonton exempt market** через мене (NRD #4575551, AB-registered, BC-registered) — твої $100-300K у Calgary multi-family MIC або industrial syndication дають **2× кращі returns** ніж BC equivalent. Я регулярно літаю Vancouver-Calgary для in-person meetings з BC клієнтами.`,
    ru: `Ванкувер — самая высокая концентрация **Accredited Investor-ов** в Канаде, но **парадокс**: BC exempt market очень **ограничен** из-за high prices + low cap rates. Лучшая стратегия для Vancouver high-net-worth: **diversify до Calgary/Edmonton exempt market** через меня (NRD #4575551, AB-registered, BC-registered).`,
    en: `Vancouver has Canada's highest concentration of **Accredited Investors** (because of high real estate equity in Vancouver homeowners), but **paradox**: BC exempt market is very **limited** due to high prices + low cap rates. Most Vancouver-based exempt market opportunities are **private credit** (debt to BC developers), not equity ownership. Better strategy for Vancouver high-net-worth: **diversify into Calgary/Edmonton exempt market** through me (NRD #4575551, AB-registered, BC-registered) — your $100-300K in a Calgary multi-family MIC or industrial syndication delivers **2× better returns** than the BC equivalent. I fly Vancouver-Calgary regularly for in-person meetings with BC clients.`,
  },

  // ─── Exempt market × Burnaby ────────────────────────────────────────────
  "exempt-market:burnaby": {
    uk: `Бернабі — Vancouver's tech corridor, тому exempt market клієнтська база тут **відрізняється від greater Vancouver**: більше high-comp engineers ($200-400K total comp), менше real-estate-equity-rich seniors. Це означає що Accredited Investor threshold ($200K income solo або $300K household) досягається типово на 4-5 рік career, плюс RSU vesting events створюють lump-sum cash для exempt market commitments. Стратегія: при RSU vesting рік — поряд із RRSP max contribution розглянь **$25-50K у Calgary multi-family REIT** через мою практику. Це диверсифікація **поза tech sector + поза BC real estate** одночасно — потужний hedge проти tech crash + BC housing correction scenarios.`,
    ru: `Бернаби — Vancouver's tech corridor, поэтому exempt market клиентская база тут **отличается от greater Vancouver**: больше high-comp engineers ($200-400K total comp), меньше real-estate-equity-rich seniors. Strategy: при RSU vesting год — рядом с RRSP max contribution рассмотри **$25-50K в Calgary multi-family REIT** через мою практику.`,
    en: `Burnaby is Vancouver's tech corridor, so exempt market client base here **differs from greater Vancouver**: more high-comp engineers ($200-400K total comp), fewer real-estate-equity-rich seniors. This means Accredited Investor threshold ($200K solo or $300K household) is typically hit in career year 4-5, plus RSU vesting events create lump-sum cash for exempt market commitments. Strategy: in RSU vesting years — alongside max RRSP contribution, consider **$25-50K in a Calgary multi-family REIT** through my practice. That's diversification **outside tech sector + outside BC real estate** simultaneously — a strong hedge against tech crash + BC housing correction scenarios.`,
  },

  // ─── RRSP × Vancouver ───────────────────────────────────────────────────
  "rrsp:vancouver": {
    uk: `Ванкувер — місто де RRSP **дуже потужний** через BC progressive tax. BC top brackets: $111K-$155K = 16.8%, $155K-$211K = 20.5%, $250K+ = 20.5% provincial. Combined federal+BC при $200K income = ~50% marginal. Кожні $10K у RRSP = **$5,000 immediate tax refund**. Стратегічна додаткова цінність — BC має **RRSP HBP $60K** як вище-описано, але через надзвичайно дорогий housing market ($800K+ average condo) HBP стає **необхідністю** не просто опцією. Strategy для Vancouver high-earner: $32K max RRSP → $16K refund → переказуй у TFSA + FHSA, через 5 років маєш $200K готівкою плюс tax shelter $160K. У retirement (lower marginal rate ~25-30% бо less income) RRSP withdrawals будуть тебе оподатковувати нижче — net win $50-100K за 25 років compounding.`,
    ru: `Ванкувер — город где RRSP **очень мощный** из-за BC progressive tax. BC top brackets: $111K-$155K = 16.8%, $155K-$211K = 20.5%, $250K+ = 20.5% provincial. Combined federal+BC при $200K income = ~50% marginal. Каждые $10K в RRSP = **$5,000 immediate tax refund**. Стратегическая дополнительная ценность — BC имеет **RRSP HBP $60K** как выше-описано, но из-за чрезвычайно дорогого housing market ($800K+ average condo) HBP становится **необходимостью** не просто опцией. Strategy для Vancouver high-earner: $32K max RRSP → $16K refund → переводи в TFSA + FHSA, через 5 лет имеешь $200K наличными плюс tax shelter $160K. В retirement (lower marginal rate ~25-30% потому что less income) RRSP withdrawals будут тебя облагать ниже — net win $50-100K за 25 лет compounding.`,
    en: `Vancouver is where RRSP is **very powerful** due to BC's progressive tax. BC top brackets: $111K-$155K = 16.8%, $155K-$211K = 20.5%, $250K+ = 20.5% provincial. Combined federal+BC at $200K income = ~50% marginal. Every $10K into RRSP = **$5,000 immediate tax refund**. Extra strategic value — BC honors **RRSP HBP $60K** as above, but Vancouver's exceptionally expensive housing market ($800K+ average condo) makes HBP a **necessity**, not just an option. Strategy for Vancouver high-earners: max $32K RRSP → $16K refund → redirect into TFSA + FHSA; in 5 years you have $200K of cash plus $160K of tax shelter. In retirement (lower marginal rate ~25-30% with less income) your RRSP withdrawals are taxed lower — net win $50-100K over 25 years of compounding.`,
  },
};

/**
 * Look up unique pair content for a specific service+city combination.
 * Returns null if no entry exists (falls through to the generic template).
 */
export function getPairContent(
  serviceSlug: string,
  citySlug: string,
  locale: Locale = 'uk',
): string | null {
  const key = `${serviceSlug}:${citySlug}`;
  const entry = PAIR_CONTENT[key];
  if (!entry) return null;
  return entry[locale] || entry.uk || null;
}
